services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/bikunewsdb
    depends_on:
      - postgres_db
    networks:
      - hono_tanstack-network
    ports:
      - "3000:3000"

  postgres_db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hono_vite_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hono_tanstack-network
    ports:
      - "5433:5432"

networks:
  hono_tanstack-network:
    driver: bridge

volumes:
  postgres-data: