import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={font.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
